### ISSUE TITLE
Unhealthy container

### ISSUE THREAD

**Issue by melyux** [dperson/samba#273] opened 2020-01-19 23:00 UTC
Not sure how long this has been around, but the container seems to be perpetually unhealthy. Getting these in the host system logs as well:

`Jan 18 05:31:06 server dockerd[551]: time="2020-01-18T05:31:06.839812804-06:00" level=warning msg="Health check for container 1a3972da731514dd6a9bf561bc6d0212e40b5f9ee4656c5f5bcee7bcac75580d error: context deadline exceeded"`

**Comment by stefanoco** [comment] 2020-01-21 11:22
Confirming here:

```bash
$
$ lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.4.1708 (Core) 
Release:        7.4.1708
Codename:       Core
$
$ sudo docker version
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:10:14 2017
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:12:46 2017
  OS/Arch:      linux/amd64
  Experimental: false
$
$ $ sudo docker ps --format "{{.ID}}: {{.Image}}, {{.Status}}"
f08fcf759a27: bluewind/samba:latest, Up 15 hours (unhealthy)
a31264c5388c: bluewind/rsync:latest, Up 15 hours
44e3fc9ca327: bluewind/viewvc:latest, Up 15 hours
```

**Comment by vueme** [comment] 2020-01-22 17:22
Hey! I believe there's something wrong with the healthcheck. Running the healthcheck manually return's error as well but the container is working just fine. I've created an issue here a few weeks ago  #267 . I've also just created my own fork of this and removed the healthcheck to prevent event-log spam and it works just fine. I might look deeper into the healthcheck thing at a later date. Cheers!

**Comment by neben** [comment] 2020-02-16 18:52
I have the same issue, the container is marked as unhealthy and I cannot connect to the share (from a Mac). This issue appeared after upgrading Docker to 19.03.6 (from 19.03.5). The docker host is an ARM-based Debian machine.

To work around the healthcheck issue for now, the healthcheck can easily be disabled by adding the `--no-healthcheck` option to the `docker run` command.

Info:
```
# docker run --name samba -p 139:139 -p 445:445 -v [...] -d dperson/samba:armhf -p [...]

# docker inspect samba
[...]
"Output": "do_connect: Connection to localhost failed (Error NT_STATUS_CONNECTION_REFUSED)\n"
"Image": "sha256:f4e3299ff23e0597e1b7eebb03a7201c4d5ce5ae95abad33ee548d9f3f36904e"
[...]

# docker version
[...]
Server: Docker Engine - Community
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.16
  Git commit:       369ce74
  Built:            Thu Feb 13 01:34:38 2020
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.2.12
  GitCommit:        35bd7a5f69c13e1563af8a93431411cd9ecf5021
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

# cat /etc/debian_version 
10.3
```

**Comment by dperson** [comment] 2020-03-20 18:23
It's working for me, I can't reproduce the errors here. If you're seeing them, but the container is running, I'd second the option to run it with the '--no-healthcheck` argument to docker.

**Closed by dperson** 2020-03-20 18:23 UTC

**Comment by Joshfindit** [comment] 2022-01-06 17:26
Related to https://github.com/dperson/samba/issues/154?

**Comment by muchtall** [comment] 2022-08-06 14:05
Posting this solution here since this was the first hit I found when searching this online.

The issue is that `\\localhost` does not resolve via normal hosts file resolution alone. If you were to run tea health check wit hte localhost IP, it would succeed:
`smbclient -L '\\127.0.0.1' -U '%' -m SMB3`

One workaround I have for this issue is to define an /etc/samba/lmhosts file with these contents:
`127.0.0.1       localhost`
Once in place, the health check succeeds.

Another option as a workaround is to change the health check itself from the command line by adding this flag:
`--health-cmd='smbclient -L '\''\\127.0.0.1'\'' -U '\''%'\'' -m SMB3'`

I personally think that this is the better option since Samba still functions fine even if it doesn't resolve localhost correctly to smbclient, thus this should be the criteria for successful start of the smb service.
